name: release

on: push
    # tags:
    #   - 'v*.*.*'
      
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: build
        run: ./src/common/write_git_info.py && cd ./src/stignore-generator && docker build -t 117503445/stignore-generator-builder -f Dockerfile_build . && docker run --rm -v $(pwd):/app 117503445/stignore-generator-builder

      # https://github.com/softprops/action-gh-release
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./src/stignore-generator/target/release/stignore-generator
